<?php

namespace AppBundle\Repository;

/**
 * ResultTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
