<?php

namespace AppBundle\Repository;

/**
 * ResultStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
